### ISSUE TITLE
Initial Release Checklist / Project Roadmap

### ISSUE THREAD

**Issue by PaulJuliusMartinez** [PaulJuliusMartinez/jless#1]
# Friends and Family Release

## Basic Functionality:
- [x] Finish basic set of movement commands
  - [x] zt, zz, zb (1910b36e7050a815221287464dae166144ea8bde)
  - [x] number arguments to hjkl/scrolling, maybe others (eb7e11623b5c4b7176150de21c08a2fcb7ae12dd, 2d11deee472c2d1501938b3490ffe5ffa7a8e56e)
    - [x] Add count support to focus prev/next sibling (`J` and `K`) (6fb6218492d62a47f002ef091a0b24fcc3e01e17)
  - [x] Support PageUp and PageDown (Move up/down by height of screen) (acf8ee3b86699700a5b40320d551569c6b75d994)
  - [x] H to focus parent without collapsing current node (ed21d5770a57b730e217859915ff4310250fbd4e)
- [x] Don't let long lines overflow horizontally (0ff12d4dadd585ac5fcb3421509fde3cc56cc50e, a1dd70e63345c033ac239701f8025023badd9b56, 849ef9714aedbe5929ddd466421a27f00d254136)
  - [x] Fix issue with displaying empty strings (3ee50d096d83da8fad4f7120b20ccfd1bf77864f)
  - [x] Update LinePrinter to handle Containers (7be34049b122ff8a24991b4e10fbd2da3bdb23c8)
- [x] Better formatting of collapsed cells in Line and Data modes (b5f29b3ed339c89e66edf919be919a483b1ff7f3)
  - [x] Quote non-JS identifier keys and all keys in Line mode (168d14f287533ba3f8f1fc831ef2feef5c64dd62)
  - [x] Write lots of tests (2396477ad6d44a3d77bd5ec1145237e715807496)
- [x] Display full controls in help menu (Just pipe to less for now; `-r` to use colored output) (fbfd8429d9c50480f3809d293ca586a81504c649, 5b898e7c2cdee5bc0ba293d36d7e496021544b6b, 458271eda55d8886494245fd6f922c2775dab6d8)
- [x] Command line arguments, `--help` documentation (ee1eb8cf01f046987f32b425135bcca3f0463919, 41a10180ad54a6f41df69e85b96d371d94e7fd90)
- [ ] Basic error handling of JSON parsing errors
- [x] Show input source in status bar (3ade459627172e79d481531421719d6c67731065)
  - [x] Make it not overflow (84600c9631a22889e508443d6a482051bdaa0370)
    - [x] Make this code not horrendous (5d15b5a339f252b4a8afa7832d527c6276bbecc4)
- [x] Pretty print JSON to stdout if output is not a TTY (04bc1ac621b96665b7baf4ba04ac1482889ed5ea)

## Polish
- [x] Properly restore terminal on close (65700114c8c786b1880cd65a41795bd0dff40d72)
- [x] Move cursor to middle of screen when jumping "far" from place on screen (b9e07c6c01083c85b59b0c07c3c93aded8a30601)
- [ ] Play visual bell at appropriate points
- [x] Immediately respond to escape key (60f0f06d972979ae1049eab140a0ab7db01ccf0b)
- [ ] Handle escape key in Rustyline (If possible to do simply)
- [x] Handle mouse wheel events (0ee52c89214d2c4640c94de0c176e88631a2482c)
- [x] Handle mouse click events (2a118732df67369e0e8e9227abdf93dda0d5364d, f2fea1e4ea89224fa575a8d1d97ae32a09184470)
  - [ ] Don't execute click event when clicking on the status bar
  - [ ] Try to figure out a way to still allow highlighting (Only do stuff on Release?)

## Release
- [x] Figure out how to actually generate release builds (bf449651685c8709a2669e360bb3902f9f68afbd)

## Development / Debug
- [ ] Add `bind` command / command-line-args for experimenting with new commands
- [ ] "Record" mode (print all input to stderr)

# Public Release

## ~ndjson
- [x] Different JSON parser (216210be4003a8567daa904f638191186cba6d8e)
- [x] Support multiple JSON objects separated by newlines (a4ecfbe6f9677cb6562a5594d41c38d770ba7bb7)
  - [ ] Actually enforce that they are separated by newlines
- [x] Fix ndjson issues/bugs
  - [x] Show focus indicator next to top level primitives in data mode (f5d8d65b9487fff855a9095277804c99568a973c)
  - [x] `G` causes panic when last top level thing is collapsed (20d5252239f15f1eacc933e373aed8732fff77dc)

## Search
- [x] Update `FlatJson` to store ranges for keys and values, and for `Row`s (05022358fe49e5dc7804f307091dd20a5288582b, a226811b98a53c53e7eae5597633c746630884ea, 5d102749499b41d27b15bb83e0b213a06ddb70c0)
- [x] Next/previous Object key with `*` and `#` (85056348284d552610d6cc6b99771db35d8753c7)
- [x] Plain text search with `/` and `?` (b9068f68645b794d96ff6118b64ed8859871acd0)
  - [x] Support `/<CR>` and `?<CR>` as longcuts for next/previous match (1c2bff81dc27280b6ef9b5dace49281a49883fa4)
- [x] Support count arguments to `n` and `N` (i.e., `3n` jumps ahead three occurrences) (6795e7b9e76590d1eac1359c03c524423991df10)
- [x] Support count arguments to `/`, `?`, `*` and `#` (814ac066ae52ad052f2bc685d358821c00f41fea)
- [x] Support smart case searching (case insensitive if all lowercase, case sensitive if any capital letters) (364174053252f24e005a3633adad17661f8ff3a3)
- [x] Escape/unescape braces and square brackets for better search experience (2fce67a09d5570c9485c85347243df6e668056a6)
- [x] Search highlighting (baf1fb31444ae86f4aee0d3ec1715b71b5693c04, c53dfa682fe06155c44257eb39f8994e2c66cb57)
  - [x] Highlight matching text in literal values (37172aef35010343509c2881308703383f492f0f)
  - [x] Highlight matching text in object keys (05d3c268469946dfcc402428b8e2ca32a60f6470)
  - [x] Highlight matching text in collapsed previews (f1015a830b94ba1f0cdd977cf0e5036a4de007d8)
  - [x] Highlight container delimiters (`[`/`]` and `{`/`}`) when part of matching text (6fe0c11713e3411d39c653dc42bfcd5626439db6, c3e7a3928c386cd79d41c0e1a0ff1990ed77e4ff)
  - [x] Highlight currently focused match in different color (c094dfb1f4864867e9679812519da9b0051dd51e)
- [ ] Handle too many search results
- [x] Show messages when no results are found (9a8108822067a25c66381c0a01db25c4440ba3dd)
  - [x] Show message when regex compilation fails (aa1d8ede91201d65092ba95d22b254e20ee78d8a)

## Focus
- [ ] `f` to "focus" on a node

## Logo
- [x] Jules the Jellyfish

## Codebase/Project Quality & Presentation
- [x] Readme (be7cfabdeb22d85898bd7b22ea21d15584ed2090)
- [x] clippy (f30d3ca16a94bd99aa241d4de6d0bb1860609d79, 3c1efd2f01ba29bc00198885f18d21b4cc15ffe5, 73af0fb8814ef3de403f7bb11aab7cd9e866e350, e9f78b24210e415a4690a3d39f504cdbe76373bc, 0a208b479fd9b6f523642c1ef6f4da8e2240ef11, 2f635c30472a025303722364fa2bae930c8b4500, 2a53257380ab54540a21a304993b4547380c9634, 931adffcef163717c762a43ac9b66b154f48d815)
- [ ] CI
- [ ] `next_visible_row` / `next_item` (either include `visible` or don't)
- [ ] General code clean up
- [ ] Commenting
- [ ] Better file structure

## Performance
- [ ] Only paint lines that need repainting
- [ ] Pack `OptionIndex` into single `usize`
- [ ] Parameterize by `u16`/`u32`/`u64` and upgrade as needed

# Unclear prioritization
- [ ] Hiding keys
- [ ] No color mode
- [ ] Explore additional commands
  - [x] `<`/`>` for adjusting indentation (e008a1506069aa6ec947f817f2624f34057e6ebb)
    - [x] Don't allow increasing indentation past max indentation in file. (b0cfaf7af3971be48938c67dd21cce3d5058399f)
  - [x] `w`/`b` for moving along same depth (cb6e82e2ebb484f819272949dd49ed885e43b6c7)
  - [x] `e`/`c` for expanding/collapsing children/siblings (de46996fb639b09a58b944695fbc52f4f059bbee, 995472bff0eeb27995b5238c1d1014c50e3b12d9)
  - [x] `,`/`.` for scrolling through long String value (7221e98216fd190433e87afd004797ea3e492f22, 95861a18f4bbc31eb953315c551fafd9eb501d94, 2c0adf99ed1fca7411a90098f15b05a8c52b71fb, 553cd38ccff6b2563270ef1e540e23c3e349299a, 00d14ce468a8da86c68d27cf30cdb718dca359c3, 7f9166f1289ac6a33d6846bd25de46ba474761a9, 655c5382d17db6010818f2980ed449fdf9822646, 87a0a65f3342f12b3e66dbd029f05d793849e0a1, e38d3d92ff5a27c6839492f66eb71f4c2f46b3a9, e176b09316ec71a07fca222901359aef81a50d97)
    - [x] `;` to skip to end / start of long String value
    - [x] Scroll horizontally to value in truncated text when searching (1e4ec96ccae7284e541b68ba4790e4808fdebbdd, 606bb9678e95f4669d3fca05226d1569717451f6)
      - [ ] Do this for labels too?
  - [ ] `!` to permanently focus on subtree
- [ ] `y` to copy value to clipboard
  - Different things to paste: `yy`, value; `yP`pretty-printed value; `yp`, path (`input.foo[0].bar[33]`); `yq`, `jq` style path, `.foo[].bar[]` ?

# Bugs
- [ ] Respond immediately to WINCH events
- [ ] Prevent flashes while scrolling (iTerm only?)
- [ ] Path to key is truncated prematurely on `long_values.json`; doesn't include last character of key

# V2
- [ ] Windows support (Need help; I don't know what this means)
- [ ] More robust syntax support for `:focus`
- [ ] Stream input
